name: Upload Docker Image
on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to hub
        run: |
          docker pull registry:latest

          docker save registry:latest | gzip > registry-latest.tar.gz

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: registry-latest.tar.gz
          path: |
            ./registry-latest.tar.gz
          retention-days: 1


