name: Upload Docker Image
on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to hub
        run: |
          docker pull splunk/splunk:8.2.3

          docker save splunk/splunk:8.2.3 | gzip > splunk:8.2.3.tar.gz

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: splunk:8.2.3.tar.gz
          path: |
            ./splunk:8.2.3.tar.gz
          retention-days: 1


